### ISSUE TITLE
list Picture module as dependency

### ISSUE THREAD

**Issue by stopfstedt** [ucsf-web-services/ucsf_images#13]
since we're implementing [theme functions](https://github.com/ucsf-drupal/ucsf_images/blob/7.x-2.7/ucsf_images.module#L119) [declared](http://drupalcontrib.org/api/drupal/drupal!core!modules!picture!picture.module/function/theme_picture_source/8) by the Picture module.

**Comment by erykmynn** [comment]
Umm no, that will break compatiblity with non-picture setups--causing problems on sites like pharm.ucsf.edu and others who don't use adaptive images.  Remember that module hooks, theme hooks, preprocess hooks do not generate a dependency because they do not get called if the caller does not exist.  This is how a lot of module compatibility is baked in to drupal modules-- it's really only calling hard functions from a module, or referencing it's table or variables that makes an actual dependency.

**Comment by erykmynn** [comment]
tl:dr; it's not a dependency because if picture doesn't exist nothing happens

**Comment by stopfstedt** [comment]
thanks @erykmynn
